POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
  "email": "fadhil@example.com",
  "password": "1234"
}

###

POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
  "fullName": "Fadhil",
  "email": "fadhil@example.com",
  "password": "1234",
  "password2": "1234"
}

###

GET http://localhost:3000/api/v1/auth/refresh

###

GET http://localhost:3000/api/v1/auth/logout

###

GET http://localhost:3000/api/v1/savings
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZhZGhpbEBleGFtcGxlLmNvbSIsInN1YiI6NCwiaWF0IjoxNjk0MTAxNDk0LCJleHAiOjE2OTQxMDE3OTR9.sX13IQIaMhJrjPszVOvHfX0aKi8HkZ5RfNZQ5YgoZeg

###

POST http://localhost:3000/api/v1/savings
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImZhZGhpbEBleGFtcGxlLmNvbSIsInN1YiI6NCwiaWF0IjoxNjk0MTAxNDk0LCJleHAiOjE2OTQxMDE3OTR9.sX13IQIaMhJrjPszVOvHfX0aKi8HkZ5RfNZQ5YgoZeg

{
  "date": "2023-09-07",
  "amount": 15000
}